sudo: false
language: python
python:
- '2.7'
services:
- postgresql
before_install:
- pip install pep8
install:
- pip install -r requirements.txt
- python setup.py install
- scripts/configure_db.py
script:
- python scripts/insert_fake_data_and_test.py
- python setup.py test
- pep8 wikithingsdb tests scripts --ignore=E501
